FROM python:3.13-slim
WORKDIR /app
RUN apt-get update && \
    apt-get install -y gdal-bin libgdal-dev libgeos-dev && \
    apt-get clean
ENV GDAL_LIBRARY_PATH=/usr/lib/libgdal.so
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]